import { Button, Col, Row, Typography } from "antd";
import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const NotFoundPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row justify="center">
        <Col md={16}>
          <Typography.Title level={1}>Uh-oh, Page not found!</Typography.Title>
          <Typography.Paragraph>
            Sorry, we could not find the page you're looking for. It may have been moved or you
            visited an invalid link.
          </Typography.Paragraph>
          <Row justify="space-around" align="middle" style={{ marginTop: "50px" }}>
            <Link href="/" passHref>
              <Button type="primary">Go Back To Home</Button>
            </Link>
          </Row>
        </Col>
      </Row>
    </div>
  );
};

export default NotFoundPage;
